### ISSUE TITLE
Formatting: keep indented comment inside else block

### ISSUE THREAD

**Issue by helixbass** [helixbass/prettier-plugin-coffeescript#134]
Something like this:
```
if isJS
  env: es6: yes
else
  # parser: ...
  parser:
    filePath: ...
    definition: ...
```
is moving the comment to above the `else` (`src/tests/code-path-analysis/code-path-analyzer.coffee` in `eslint-plugin-coffee`)
